name: creditsea_app
description: Loan application mobile app for CreditSea
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0
  lottie: ^2.7.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "#004C99"
  image: assets/images/Group.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/images/Group.png
    - assets/images/image 1.png
    - assets/images/card.png
    - assets/animation/Increasing Coin Animation.json